# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d550345aa79c8a1ff9a8fde64518f350707f2b1af7dda818d0054e921fe434d90659e287234a6a0610550a5bd4a1d830b73dd7a8dd556d8dccc638aa2bc749e

test:
  secret_key_base: 52cfe1d25bd97263ca063edf957cbc0e058aecbfd41347b5894a24001b0ac569b9a7af6d9c7184a3f09430e9cef2d654c260f32ef44a7a1c79a089dcded72e7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
